nameOverride: ""
fullnameOverride: ""

# Broker (Temporal Worker) configuration
broker:
  replicaCount: 2
  image:
    repository: crawler/broker
    tag: latest
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Broker Manager (REST API + Temporal Client) configuration
brokerManager:
  replicaCount: 2
  image:
    repository: crawler/broker-manager
    tag: latest
    pullPolicy: IfNotPresent
  
  service:
    type: NodePort
    port: 8080
    nodePort: 30080
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Temporal server (development only)
temporal:
  image:
    repository: temporalio/auto-setup
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    port: 7233
    metricsPort: 8233
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

# PostgreSQL (development only)
postgres:
  image:
    repository: postgres
    tag: 16
    pullPolicy: IfNotPresent
  replicaCount: 1
  persistence:
    enabled: false 
  service:
    port: 5432
  resources:
    requests:
      cpu: 100m
      memory: 128Mi 