apiVersion: v1
kind: Service
metadata:
  name: {{ include "crawler.fullname" . }}-broker-manager
  labels:
    app: {{ include "crawler.name" . }}-broker-manager
    chart: {{ include "crawler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.brokerManager.service.type }}
  ports:
    - port: {{ .Values.brokerManager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.brokerManager.service.nodePort }}
  selector:
    app: {{ include "crawler.name" . }}-broker-manager
    release: {{ .Release.Name }} 