apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crawler.fullname" . }}-broker-manager
  labels:
    app: {{ include "crawler.name" . }}-broker-manager
    chart: {{ include "crawler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.brokerManager.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "crawler.name" . }}-broker-manager
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "crawler.name" . }}-broker-manager
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: broker-manager
          image: "{{ .Values.brokerManager.image.repository }}:{{ .Values.brokerManager.image.tag }}"
          imagePullPolicy: {{ .Values.brokerManager.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: TEMPORAL_ADDRESS
              value: '{{ include "crawler.fullname" . }}-temporal:7233'
            - name: TEMPORAL_NAMESPACE
              value: "default"
            - name: DB_HOST
              value: '{{ include "crawler.fullname" . }}-postgres'
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "crawler"
            - name: GIN_MODE
              value: "release"
          resources:
            {{- toYaml .Values.brokerManager.resources | nindent 12 }} 