apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crawler.fullname" . }}-service2
  labels:
    app: {{ include "crawler.name" . }}-service2
    chart: {{ include "crawler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.service2.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "crawler.name" . }}-service2
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "crawler.name" . }}-service2
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: service2
          image: "{{ .Values.service2.image.repository }}:{{ .Values.service2.image.tag }}"
          imagePullPolicy: {{ .Values.service2.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: TEMPORAL_ADDRESS
              value: "host.minikube.internal:8233"
            - name: TEMPORAL_NAMESPACE
              value: "default"
            - name: DB_HOST
              value: "host.minikube.internal"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "crawler"
            - name: GIN_MODE
              value: "release"
          resources:
{{ toYaml .Values.service2.resources | indent 12 }} 