apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crawler.fullname" . }}-broker
  labels:
    app: {{ include "crawler.name" . }}-broker
    chart: {{ include "crawler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.broker.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "crawler.name" . }}-broker
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "crawler.name" . }}-broker
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: broker
          image: "{{ .Values.broker.image.repository }}:{{ .Values.broker.image.tag }}"
          imagePullPolicy: {{ .Values.broker.image.pullPolicy }}
          env:
            - name: TEMPORAL_ADDRESS
              value: '{{ include "crawler.fullname" . }}-temporal:7233'
            - name: TEMPORAL_NAMESPACE
              value: "default"
          resources:
            {{- toYaml .Values.broker.resources | nindent 12 }} 