apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crawler.fullname" . }}-temporal
  labels:
    app: {{ include "crawler.name" . }}-temporal
    chart: {{ include "crawler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.temporal.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "crawler.name" . }}-temporal
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "crawler.name" . }}-temporal
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: temporal
          image: "{{ .Values.temporal.image.repository }}:{{ .Values.temporal.image.tag }}"
          imagePullPolicy: {{ .Values.temporal.image.pullPolicy }}
          env:
            - name: DB
              value: postgres12
            - name: POSTGRES_SEEDS
              value: {{ printf "%s-postgres" (include "crawler.fullname" .) | quote }}
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PWD
              value: "password"
            - name: DB_PORT
              value: "{{ .Values.postgres.service.port }}"
          ports:
            - name: grpc
              containerPort: 7233
              protocol: TCP
          resources:
            {{- toYaml .Values.temporal.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crawler.fullname" . }}-temporal
  labels:
    app: {{ include "crawler.name" . }}-temporal
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.temporal.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ include "crawler.name" . }}-temporal
    release: {{ .Release.Name }} 